


# Spring Profile Configuration
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=SmartHire

# Common Server Configuration
server.error.include-message=always
server.error.include-binding-errors=always

# Common JPA Configuration
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Common File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Common Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# Common Security
spring.security.user.name=admin
spring.security.user.password=admin